"""Fixes an issue in the relationship between connections and users

Revision ID: 40681c58c550
Revises: 81185b98fdf7
Create Date: 2025-02-14 14:18:55.714222

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '40681c58c550'
down_revision = '81185b98fdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_auth_connection_user',  # Explicit name for the foreign key
            'user',
            ['user_id'],
            ['fs_uniquifier']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication_connection', schema=None) as batch_op:
        batch_op.drop_constraint('fk_auth_connection_user', type_='foreignkey')  # Use the explicit name
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
